//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ºActividadADATconEntity.BBDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Actividad1_AccesoADatosEntities : DbContext
    {
        public Actividad1_AccesoADatosEntities()
            : base("name=Actividad1_AccesoADatosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EquiposFutbolTitulos> EquiposFutbolTitulos { get; set; }
        public virtual DbSet<TenistasTitulos> TenistasTitulos { get; set; }
    }
}
