//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ºActividadADATconEntity.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposFutbolTitulos
    {
        public int idEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public Nullable<int> Champions { get; set; }
        public Nullable<int> Ligas { get; set; }
        public Nullable<int> CopasDelRey { get; set; }
        public Nullable<int> Supercopas { get; set; }
    }
}
