//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ºActividadADATconEntity.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenistasTitulos
    {
        public int idTenista { get; set; }
        public string NombreTenista { get; set; }
        public Nullable<int> GrandSlam { get; set; }
        public Nullable<int> AbiertoDeAustralia { get; set; }
        public Nullable<int> RolanGarros { get; set; }
        public Nullable<int> Wimbledon { get; set; }
    }
}
